### PR TITLE
V4.2 rc2

### PR DESCRIPTION
**Pull request by larsvilhuber**
Only difference to V4.2-rc1 is #81

### CODE REVIEW

**Comment by srt1** [comment]
Yes, looks like a lot of stuff.

________________________________

**Comment by heathhayward** [comment]
should https://github.com/labordynamicsinstitute/qwi_schemas/blob/V4.2-rc2/formats/V4.2-rc2/lags_j2japp.csv be in rc2 consider that the variables_j2japp.csv file and all references to J2J Explorer have been removed?   

Also, should there be lags_j2jr and lags_j2jod csvs listed here?

**Comment by larsvilhuber** [comment]
Thanks for catching the incomplete removal of the j2japp stuff. will handle.


lags_j2jr and lags_j2jod are included in the overall description, that wasn't part of #81, and I believe we had discussed that in a different ticket (and finalized that).


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
Also, in the "Changes" section, we should remove the line: Added J2J Explorer-specific description of metadata for convenience (lehd_j2jexplorer_schema.html)

**Comment by heathhayward** [comment]
Will the 2 commits that you just did appear in https://github.com/labordynamicsinstitute/qwi_schemas/blob/V4.2-rc2/formats/V4.2-rc2/lehd_public_use_schema.asciidoc at some point?

**Comment by heathhayward** [comment]
this release candidate looks good to me.

**Comment by srt1** [comment]
Heath gave me a link to the asciidoc version, which I always have a hard time finding (sorry about that). I don't see anything else.

________________________________

**Comment by larsvilhuber** [comment]
Based on the comments, pulling this into MASTER, will then rename to V4.2.0

**Pull request merged**
